apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-ui
  labels:
    app: client-ui
spec:
  selector:
    matchLabels:
      app: client-ui
  template:
    metadata:
      name: client-ui
      labels:
        app: client-ui
    spec:
      containers:
        - name: client-ui
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
